config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :events, only: %i[index show new create] do
    resources :bookings, only: :create
  end

  namespace :user, module: 'user_data' do
    resources :organized_events, only: :index
    resources :attended_events, only: %i[index show]
  end

  get 'sign-up' => 'users#new'
  post 'sign-up' => 'users#create'
  post 'sign-in' => 'sessions#create'
  delete 'sign-out' => 'sessions#destroy'

  # Defines the root path route ("/")
  root "sessions#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :user, optional: false
  has_many :tickets, inverse_of: :event

  validates :name, :total_tickets, :datetime, :latitude, :longitude, presence: true

  scope :upcoming, -> { where(datetime: Time.current..) }
end

app/models/ticket.rb
# frozen_string_literal: true

class Ticket < ApplicationRecord
  belongs_to :event, optional: false
  belongs_to :user, optional: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  has_many :events, inverse_of: :user
  has_many :tickets, inverse_of: :user

  validates :name, presence: true
  validates :password, length: { minimum: 6 }
  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user

  private

  attr_reader :current_user

  def authenticate_user
    return redirect_to root_path if session[:user_id].blank?

    user = User.find_by(id: session[:user_id])

    if user.blank?
      session.delete(:user_id)
      return redirect_to root_path
    end

    @current_user = user
  end
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

class BookingsController < ApplicationController
  def create
    @booked_tickets_count = BookEventTickets.new(user: current_user, event: event, tickets_count: tickets_count).call

    if @booked_tickets_count.zero?
      render partial: 'events/show/booking_result', status: :unprocessable_entity
    else
      redirect_to event_path(event.id), flash: { notice: "Successfully booked #{@booked_tickets_count} ticket(s)" }
    end
  end

  private

  def event
    @event ||= Event.find(params[:event_id])
  end

  def tickets_count
    params[:tickets_count].to_i
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def index
    @events = Rails.cache.fetch('upcoming_events', expires_in: 5.minutes) do
      Event.upcoming.to_a
    end

    @tickets_left = @events.each_with_object({}) { |event, obj| obj[event.id] = tickets_left(event) }
  end

  def show
    @event = Event.find(params[:id])
    @tickets_left = tickets_left(@event)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(user: current_user, **event_params.merge(latitude: 1, longitude: 1))

    if @event.save
      CreateTicketsJob.perform_async(@event.id, @event.total_tickets)
      redirect_to event_path(@event.id)
    else
      render :new
    end
  end

  private

  def tickets_left(event)
    event.total_tickets - BookedTicketsCounter.new(event).count
  end

  def event_params
    params.require(:event).permit(:name, :description, :datetime, :latitude, :longitude, :total_tickets)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  layout 'id'
  skip_before_action :authenticate_user

  def new
    return redirect_to events_path if session[:user_id].present?

    @user = User.new
  end

  def create
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to events_path
    else
      render partial: 'sessions/new/alert_response',
             locals: { message: 'Email or password is not correct' },
             status: :unprocessable_entity
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end

  private

  def user
    return @user if defined?(@user)

    @user = User.find_by(email: session_params[:email])
  end

  def session_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/user_data/attended_events_controller.rb
# frozen_string_literal: true

module UserData
  class AttendedEventsController < ApplicationController
    def index
      # @tickets = Ticket.where(user: current_user).group(:event_id).select('event_id, COUNT(*) as tickets_count').includes(:event)
      @events = Event.joins(:tickets)
                     .where(tickets: { user: current_user })
                     .group('events.id, events.name, events.datetime')
                     .select('events.id, events.name, events.datetime, COUNT(*) as tickets_count')
    end

    def show
      @tickets = Ticket.where(user_id: current_user.id, event_id: params[:id])
    end
  end
end

app/controllers/user_data/organized_events_controller.rb
# frozen_string_literal: true

module UserData
  class OrganizedEventsController < ApplicationController
    def index
      @events = Event.where(user: current_user)
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  layout 'id'
  skip_before_action :authenticate_user

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to events_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.haml
- turbo_page_requires_reload
.container.mt-5
  %h1.text-secondary.text-center.mb-5
    %span.text-primary Meetups!

  .row
    .col-6.offset-3
      = link_to 'New Event', new_event_path, class: 'btn btn-primary btn-block w-100'

  .row.mt-5
    .col-12
      - @events.each do |event|
        - tickets_left = @tickets_left[event.id]
        - cache [event, tickets_left]  do
          = render partial: 'events/index/event', locals: { event: event, tickets_left: tickets_left }

app/views/events/index/_event.html.haml
%a.text-decoration-none{href: event_path(event)}
  .row
    .col-6.offset-3
      %h3= event.name
  .row
    .col-6.offset-3
      %h4.text-secondary= event.datetime.strftime("%a, %B %d %T")
  .row
    .col-6.offset-3
      %h4.text-secondary= "#{tickets_left}/#{event.total_tickets}"
  %hr.text-secondary.my-3

app/views/events/new.html.haml
.container.mt-5
  %h1.text-secondary.text-center
    Create
    %span.text-primary Meetup!

  = simple_form_for @event, method: :post, defaults: { label_html: { class: 'text-start' } } do |form|
    .row.mt-5
      .col-6.offset-3
        = form.input :name, placeholder: 'Name'

    .row.mt-2
      .col-6.offset-3
        = form.input :datetime, placeholder: 'Date'

    .row.mt-2
      .col-6.offset-3
        = form.input :description, placeholder: 'Description'

    .row.mt-2
      .col-6.offset-3
        = form.input :total_tickets, placeholder: 'Available Tickets'

    .row.mt-3
      .col-6.offset-3
        = form.submit 'Create Event', class: 'btn btn-primary btn-block w-100'

app/views/events/show.html.haml
.container.mt-5
  %h1.text-secondary.text-center
    = @event.name
    %span.text-primary Meetup!

  .text-center.my-3
    %a.rounded.text-decoration-none{href: events_path} < Back to events

  .row
    .col-6.offset-3
      %h4.text-secondary= @event.datetime.strftime("%a, %B %d %T")
  .row.mt-2
    .col-6.offset-3
      %h4.text-secondary= @event.description
  .row
    .col-4.offset-4
      %h4= "#{@tickets_left}/#{@event.total_tickets}"

  .row
    .col-6.offset-3
      %turbo-frame#booking_result
        - if flash[:notice].present?
          .alert.alert-success
            = flash[:notice]

  .row.my-5
    .col-12.text-center
      = simple_form_for(@event, url: event_bookings_path(@event.id), method: :post, html: { data: { 'turbo-frame'=> 'booking_result' } }) do |f|
        = number_field_tag :tickets_count
        = f.submit 'Book tickets', class: 'btn btn-primary'

app/views/events/show/_booking_result.html.haml
%turbo-frame#booking_result
  - if @booked_tickets_count.zero?
    .alert.alert-danger
      Sorry, we were not able to book the requested number of tickets

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meetup</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="<%= root_path %>">Meetup</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="<%= events_path %>">Events</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                User data
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="<%= user_organized_events_path %>">Organized Events</a></li>
                <li><a class="dropdown-item" href="<%= user_attended_events_path %>">Attending Events</a></li>
              </ul>
            </li>
          </ul>
          <form class="d-flex">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to "Logout", sign_out_path, data: { turbo_method: :delete }, class: "nav-link active" %>
              </li>
            </ul>
          </form>
          </form>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/layouts/id.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meetup</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/user_data/attended_events/index.html.haml
.container.mt-5
  %h1.text-secondary.text-center.mb-5
    %span.text-primary Meetups you're attending

  - @events.each do |event|
    %a.text-decoration-none{href: user_attended_event_path(event)}
      .row
        .col-4
          %h3= event.name
        .col-4
          %h4.text-secondary= event.datetime.strftime("%a, %B %d %T")
        .col-4
          %h4.text-secondary= event.tickets_count

app/views/user_data/attended_events/show.html.haml
.container.mt-5
  %h1.text-secondary.text-center.mb-5
    %span.text-primary Your tickets

  - @tickets.each do |ticket|
    .row
      .col-4
        %h3
          Ticket number:
          = ticket.id
      .col-4
        %h4.text-secondary
          Booked At:
          = ticket.updated_at.strftime("%a, %B %d %T")

app/views/user_data/organized_events/index.html.haml
.container.mt-5
  %h1.text-secondary.text-center.mb-5
    %span.text-primary Meetups you organize!

  - @events.each do |event|
    %a.text-decoration-none{href: event_path(event)}
      .row
        .col-6.offset-3
          %h3= event.name
      .row
        .col-6.offset-3
          %h4.text-secondary= event.datetime.strftime("%a, %B %d %T")
      %hr.text-secondary.my-3

app/views/users/new.html.haml
.container.mt-5
  %h1.text-secondary.text-center
    Welcome to
    %span.text-primary Meetup!

  %h2.text-secondary.text-center.mt-5 Sign Up

  = simple_form_for @user, url: sign_up_path, method: :post, defaults: { label_html: { class: 'text-start' } } do |form|
    .row.mt-5
      .col-6.offset-3
        = form.input :name, placeholder: 'Name'

    .row.mt-2
      .col-6.offset-3
        = form.input :email, placeholder: 'E-Mail'

    .row.mt-2
      .col-6.offset-3
        = form.input :password, placeholder: 'Password'

    .row.mt-3
      .col-6.offset-3
        = form.submit 'Create an account', class: 'btn btn-primary btn-block w-100'

    .row.mt-2
      .col-6.offset-3
        = link_to('Sign in', root_path)